### ISSUE TITLE
Inventory Setup

### ISSUE THREAD

**Issue by mdtabrezpasha** [neilmunday/Salt-Minion-Inventory#37] opened 2022-07-13 18:16 UTC
Hi Neil,
            i am trying to setup the inventory system for my salt master.  have configured everthing as per your instructions.  getting this error " root@saltsrv:/var/lib/salt/runners# salt labtest-ubuntu inventory.audit force=True
labtest-ubuntu:
    'inventory.audit' is not available.
ERROR: Minions returned with non-zero exit code"

![image](https://user-images.githubusercontent.com/50145580/178803076-9f606dc0-3a15-4052-9cba-d1fa8849f8f9.png)

plz advise.

**Comment by mdtabrezpasha** [comment] 2022-07-13 18:30
we are using the latest version of salt-master 3004.2.  would be very helpful if you can post a step by step install instructions.

**Comment by mdtabrezpasha** [comment] 2022-07-14 06:20
Hi Niel Thanks for responding so quickly. I think your setup instructions are for experienced tech.   I am sure I am making a mistake in the MySQL setup too.  Consider me a noob, will be very helpful if you can send me detailed setup instructions.  

 

Thanks in advance.

**Comment by neilmunday** [comment] 2022-07-14 20:27
@mdtabrezpasha can you please try the debugging tasks I mentioned above including the `python` command?

On the MySQL front, the minions do not perform any MySQL calls - this is done on the Salt master.

**Comment by mdtabrezpasha** [comment] 2022-07-15 15:49
Hi Neil,  i ran python3 /srv/salt/_modules/inventory.py no errors.  

master log file shows "[salt.utils.reactor:417 ][ERROR   ][24110] Reactor 'inventory_present' failed to execute runner 'inventory.present': function not available"

debug output

salt -l debug '*' inventory.audit force=True
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] Override  __grains__: <module 'salt.loaded.int.log_handlers.sentry_mod' from '/usr/lib/python3/dist-packages/salt/log/handlers/sentry_mod.py'>
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Popen(['git', 'version'], cwd=/home/zerodha/Salt-Minion-Inventory/srv, universal_newlines=False, shell=None, istream=None)
[DEBUG   ] Popen(['git', 'version'], cwd=/home/zerodha/Salt-Minion-Inventory/srv, universal_newlines=False, shell=None, istream=None)
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.10.20.36:4506
[DEBUG   ] Trying to connect to: tcp://10.10.20.36:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/fe/5fe67a392460fc76d1816723971ec1e06671c01b80b8252699d81110db2ac5/.minions.p
[DEBUG   ] get_iter_returns for jid 20220715154544152950 sent to {'labtest-ubuntu'} will timeout at 15:45:49.184956
[DEBUG   ] jid 20220715154544152950 return from labtest-ubuntu
[DEBUG   ] return event: {'labtest-ubuntu': {'ret': "'inventory.audit' is not available.", 'out': 'nested', 'retcode': 1, 'jid': '20220715154544152950'}}
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded nested.output
labtest-ubuntu:
    'inventory.audit' is not available.
[DEBUG   ] jid 20220715154544152950 found all minions {'labtest-ubuntu'}
[DEBUG   ] Closing IPCMessageSubscriber instance
ERROR: Minions returned with non-zero exit code

Web ui also has error

![salt inventory web ui error](https://user-images.githubusercontent.com/50145580/179259772-d020e5ef-5e9b-4124-aa82-6dc4857743b5.png)
![salt inventory web ui error](https://user-images.githubusercontent.com/50145580/179259772-d020e5ef-5e9b-4124-aa82-6dc4857743b5.png)

**Comment by neilmunday** [comment] 2022-07-15 20:25
Thanks for the info. Another user has also confirmed that there is an issue with Salt 3004. I am looking into it.

**Comment by neilmunday** [comment] 2022-07-15 22:56
After futher testing I think the issue might be due to the Python MySQL module not being installed on your salt master.

Can you check that this module is installed please?

E.g.

```
pip3 list | grep mysqlclient
```

On Red Hat based systems the package that provides this module is called `python3-mysql`. I'm not an Ubuntu user but I think the corresponding package for this OS has the same name.

**Comment by neilmunday** [comment] 2022-07-29 21:36
Closing due to no reply. Will re-open if needed.

**Closed by neilmunday** 2022-07-29 21:36 UTC
Labels: help wanted

**Comment by mdtabrezpasha** [comment] 2022-10-11 08:24
Hi Neil,

             I have run pip3 list | grep mysqlclient,  no errors, but nothing in the list.

 



 

 

salt -l debug '*' inventory.audit force=True

[DEBUG   ] Reading configuration from /etc/salt/master

[DEBUG   ] Missing configuration file: /root/.saltrc

[DEBUG   ] Using importlib_metadata to load entry points

[DEBUG   ] Override  __grains__: <module 'salt.loaded.int.log_handlers.sentry_mod' from '/usr/lib/python3/dist-packages/salt/log/handlers/sentry_mod.py'>

[DEBUG   ] Configuration file path: /etc/salt/master

[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.

[DEBUG   ] Reading configuration from /etc/salt/master

[DEBUG   ] Missing configuration file: /root/.saltrc

[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc

[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc

[DEBUG   ] Popen(['git', 'version'], cwd=/home/zerodha, universal_newlines=False, shell=None, istream=None)

[DEBUG   ] Popen(['git', 'version'], cwd=/home/zerodha, universal_newlines=False, shell=None, istream=None)

[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.10.20.36:4506

[DEBUG   ] Trying to connect to: tcp://10.10.20.36:4506

[DEBUG   ] Closing AsyncZeroMQReqChannel instance

[DEBUG   ] LazyLoaded local_cache.get_load

[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/40/bf83c00d6769595e7bd22cc54015cd7318923e2ffb6132beb57f30fcb9b10c/.minions.p

[DEBUG   ] get_iter_returns for jid 20220716045923752641 sent to {'labtest-ubuntu'} will timeout at 04:59:28.774153

[DEBUG   ] jid 20220716045923752641 return from labtest-ubuntu

[DEBUG   ] return event: {'labtest-ubuntu': {'ret': "'inventory.audit' is not available.", 'out': 'nested', 'retcode': 1, 'jid': '20220716045923752641'}}

[DEBUG   ] Using importlib_metadata to load entry points

[DEBUG   ] LazyLoaded nested.output

labtest-ubuntu:

    'inventory.audit' is not available.

[DEBUG   ] jid 20220716045923752641 found all minions {'labtest-ubuntu'}

[DEBUG   ] Closing IPCMessageSubscriber instance

ERROR: Minions returned with non-zero exit cod

**Comment by neilmunday** [comment] 2022-10-11 22:03
Ok, so sounds like to me that the Python `mysqlclient` module is not installed if the `grep` command is returning no results. Please install this package for your OS.
